SELECT DISTINCT  ?result ?score
WHERE
  { { { { { VALUES ?radius { 10 }
            ?result  a                     <http://purl.org/webofneeds/model#Need> ;
                     <http://purl.org/webofneeds/model#isInState>  <http://purl.org/webofneeds/model#Active> .
            ?result (<http://purl.org/webofneeds/model#seeks>)?/((((<http://purl.org/webofneeds/model#hasLocation>|<http://schema.org/jobLocation>)|<http://schema.org/location>)|<http://schema.org/fromLocation>)|<http://schema.org/toLocation>) ?location .
            ?location  <http://schema.org/geo>  ?location_geo
          }
          SERVICE <http://www.bigdata.com/rdf/geospatial#search>
            { ?location_geo
                        <http://www.bigdata.com/rdf/geospatial#search>  "inCircle" ;
                        <http://www.bigdata.com/rdf/geospatial#searchDatatype>  <http://www.bigdata.com/rdf/geospatial/literals/v1#lat-lon> ;
                        <http://www.bigdata.com/rdf/geospatial#predicate>  <http://purl.org/webofneeds/model#geoSpatial> ;
                        <http://www.bigdata.com/rdf/geospatial#spatialCircleCenter>  "48.22507335#16.3583975990458" ;
                        <http://www.bigdata.com/rdf/geospatial#spatialCircleRadius>  ?radius ;
                        <http://www.bigdata.com/rdf/geospatial#distanceValue>  ?location_geoDistance}
        }
        FILTER ( ?location_geoDistance < ?radius )
        FILTER NOT EXISTS { ?result  <http://purl.org/webofneeds/model#hasFlag>  <http://purl.org/webofneeds/model#NoHintForCounterpart> }
        FILTER NOT EXISTS { ?result  <http://purl.org/webofneeds/model#hasFlag>  <http://purl.org/webofneeds/model#WhatsNew> }
        FILTER NOT EXISTS { ?result  <http://purl.org/webofneeds/model#hasFlag>  <http://purl.org/webofneeds/model#WhatsAround> }
      }
      BIND(( ( ?radius - ?location_geoDistance ) / ?radius ) AS ?score)
    }
    FILTER NOT EXISTS { ?result  <http://purl.org/webofneeds/model#hasFlag>  <http://purl.org/webofneeds/model#NoHintForCounterpart> }
  }
