prefix dc:    <http://purl.org/dc/elements/1.1/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix conn:  <http://localhost:8080/won/resource/connection/>
prefix event: <http://localhost:8080/won/resource/event/>
prefix woncrypt: <https://w3id.org/won/core#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix local: <http://localhost:8080/won/resource/>
prefix won:   <https://w3id.org/won/core#>
prefix msg:   <https://w3id.org/won/message#>
prefix signature: <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#>
prefix ldp:   <http://www.w3.org/ns/ldp#>

# true => there is an object of msg:messageType that has unknown type uri
ASK
{
  SELECT (count(?subj) as ?num) WHERE
  {
    GRAPH ?graph
    {
       ?subj msg:messageType ?type
       FILTER (?type != msg:CreateMessage  &&  ?type != msg:ConnectMessage
            && ?type != msg:ReplaceMessage 
            && ?type != msg:CloseMessage && ?type != msg:ConnectionMessage 
            && ?type != msg:AtomHintMessage && ?type != msg:SocketHintMessage
            && ?type != msg:DeleteMessage
            && ?type != msg:FailureResponse && ?type != msg:SuccessResponse
            && ?type != msg:ActivateMessage && ?type != msg:DeactivateMessage
            && ?type != msg:OpenMessage && ?type != msg:HintFeedbackMessage
            && ?type != msg:AtomMessage && ?type != msg:ChangeNotificationMessage)
    } 
  }
  HAVING (?num > 0)
}