# find all content graphs, make sure they contain no triples with properties from the msg namespace

prefix msg:   <https://w3id.org/won/message#>

SELECT
  (count(distinct(?p)) as ?numMsgPropsInContent)   # number of properties from msg namespace in message content (must be 0) 
  (if(?numMsgPropsInContent = 0, "OK", "FAIL") AS ?check)
WHERE
{
  { 
    SELECT ?contentGraph where { GRAPH ?g { ?x msg:content ?contentGraph} } 
  }
  { 
    GRAPH ?contentGraph 
    { 
      ?s ?p ?o 
      FILTER (STRSTARTS(str(?p),"https://w3id.org/won/message#"))
    } 
  } 
}
