prefix dc:    <http://purl.org/dc/elements/1.1/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix conn:  <http://localhost:8080/won/resource/connection/>
prefix event: <http://localhost:8080/won/resource/event/>
prefix woncrypt: <http://purl.org/webofneeds/woncrypt#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix local: <http://localhost:8080/won/resource/>
prefix won:   <http://purl.org/webofneeds/model#>
prefix msg:   <http://purl.org/webofneeds/message#>
prefix signature: <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#>
prefix ldp:   <http://www.w3.org/ns/ldp#>


# true => there are no subjects with properties of message that additionally have rdf:type property
ASK
{
  SELECT (count(?subj) as ?num) WHERE
  {
    GRAPH ?graph
    {
            ?subj rdf:type ?type .
            ?subj msg:hasMessageType|msg:hasContent|msg:hasReceivedTimestamp|msg:hasSentTimestamp|msg:hasReceiver|msg:hasSender|msg:hasReceiverNeed|msg:hasSenderNeed|msg:hasReceiverNode|msg:hasSenderNode|msg:isResponseTo|msg:isRemoteResponseTo|msg:isResponseToMessageType ?propobj
            FILTER (?type != msg:FromSystem && ?type != msg:FromExternal && ?type != msg:FromOwner)
    } .
  }
  HAVING (?num > 0)
}