prefix dc:    <http://purl.org/dc/elements/1.1/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix conn:  <http://localhost:8080/won/resource/connection/>
prefix event: <http://localhost:8080/won/resource/event/>
prefix woncrypt: <https://w3id.org/won/core#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix local: <http://localhost:8080/won/resource/>
prefix won:   <https://w3id.org/won/core#>
prefix msg:   <https://w3id.org/won/message#>
prefix signature: <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#>
prefix ldp:   <http://www.w3.org/ns/ldp#>


# true => there are no subjects with properties of message that additionally have rdf:type property
#TODO can check missing and invalid at the same time... ? should be in each envelope or for each event?
ASK
{
  SELECT (count(?subj) as ?num) WHERE
  {
    GRAPH ?graph
    {
            ?subj rdf:type ?obj .
            ?subj msg:messageType|msg:content|msg:receivedTimestamp|msg:sentTimestamp|msg:recipient|msg:sender|msg:recipientAtom|msg:senderAtom|msg:recipientNode|msg:senderNode|msg:isResponseTo|msg:isRemoteResponseTo|msg:isResponseToMessageType ?propobj
    } .
  }
  HAVING (?num < 1)
}