PREFIX won: <http://purl.org/webofneeds/model#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX s: <http://schema.org/>
PREFIX geo: <http://www.bigdata.com/rdf/geospatial#>
PREFIX geoliteral: <http://www.bigdata.com/rdf/geospatial/literals/v1#>
SELECT DISTINCT ?result ?score WHERE {
  OPTIONAL {
    SELECT DISTINCT ?result ?industry_jaccardIndex WHERE {
      {
        SELECT ?result (SUM(?var0) AS ?targetOverlap) (COUNT(?result) AS ?targetTotal) WHERE {
          ?result s:industry ?tag.
          BIND(IF((STR(?tag)) = "KarosseriebauerIn", 1 , 0 ) AS ?var0)
        }
        GROUP BY ?result
      }
      BIND(?targetOverlap / ((?targetTotal + 1 ) - ?targetOverlap) AS ?industry_jaccardIndex)
      FILTER(?industry_jaccardIndex > 0 )
    }
  }
  OPTIONAL {
    SELECT ?result ?jobLocation_geoScore WHERE {
      ?result (s:jobLocation/s:geo) ?geo.
      {
      SERVICE geo:search {
        ?geo geo:search "inCircle";
          geo:searchDatatype geoliteral:lat-lon;
          geo:predicate won:geoSpatial;
          geo:spatialCircleCenter "48.22350935259615#16.38684868812561";
          geo:spatialCircleRadius "10";
          geo:distanceValue ?geoDistance.
      }
      BIND((10  - ?geoDistance) / 10  AS ?geoScoreRaw)
      }
      BIND(IF(?geoScoreRaw > 0 , ?geoScoreRaw, 0 ) AS ?jobLocation_geoScore)
    }
  }
  ?result rdf:type won:Need, s:JobPosting.
  BIND((((((COALESCE(?industry_jaccardIndex, 0 )) + (COALESCE(?skills_jaccardIndex, 0 ))) + (COALESCE(?organizationName_jaccardIndex, 0 ))) + (COALESCE(?employmentTypes_jaccardIndex, 0 ))) + (COALESCE(?jobLocation_geoScore, 0 ))) / 5  AS ?score)
}
ORDER BY DESC (?score)