PREFIX match: <https://w3id.org/won/matching#>
prefix won: <https://w3id.org/won/core#>
prefix rdfs: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?slice ?atom ?value WHERE {
    BIND('seeks_title' as ?slice)
    ?atom rdfs:type won:Atom.
    ?atom won:crawlStatus ?crawlStatus.
    ?atom won:crawlDate ?date.
    ?atom won:atomState won:Active.
    ?atom match:seeks/dc:title ?value.
    OPTIONAL {?atomUri match:flag ?flag}.
    FILTER (!bound(?flag) || (?flag != won:DoNotMatch && ?flag != match:UsedForTesting))
    FILTER (?date >= ?from && ?date < ?to)  # bind variables ?from and ?to here
    FILTER (?crawlStatus = 'DONE' || ?crawlStatus = 'SAVE')
} 