# each envelope must be subgraph of exactly one message
PREFIX msg: <https://w3id.org/won/message#>
PREFIX rdfg: <http://www.w3.org/2004/03/trix/rdfg-1/>
SELECT ?msg ?msgType ?g WHERE {
	?msg msg:messageType ?msgType .
  	?msg2 msg:messageType ?msgType .
    ?g a msg:EnvelopeGraph ;
       rdfg:subGraphOf ?msg ;
       rdfg:subGraphOf ?msg2
    FILTER (?msg != ?msg2)
}