/*
 * Copyright 2012  Research Studios Austria Forschungsges.m.b.H.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package won.protocol.service;
import won.protocol.model.Need;

import java.net.URI;

/**
 * Service for creating and manipulating needs.
 * TODO [REFACTORING]: delete and move methods to owner and node interfaces.
 */
public interface NeedManagementServiceRefactoring
{

  //TODO: shouldn't the ownerApplicationId be generated by the node?
  public void authorizeOwnerApplicationForNeedURI(final String ownerApplicationID, URI needURI);

  void authorizeOwnerApplicationForNeed(String ownerApplicationID, Need need);


}
