 ALTER TABLE message_event RENAME COLUMN receiverneeduri TO recipientatomuri ;
 ALTER TABLE message_event RENAME COLUMN receivernodeuri TO recipientnodeuri ;
 ALTER TABLE message_event RENAME COLUMN receiveruri TO recipienturi ;
 ALTER TABLE message_event RENAME COLUMN senderneeduri TO senderatomuri ;
 ALTER TABLE message_event RENAME COLUMN eventcontainer_id TO messagecontainer_id ;
 ALTER TABLE need_rdf_datasets RENAME COLUMN need_id TO atom_id ;
 ALTER TABLE need RENAME COLUMN needuri TO atomuri ;
 ALTER TABLE need RENAME COLUMN event_container_id TO message_container_id ;
 ALTER TABLE bastate RENAME COLUMN facettypeuri TO sockettypeuri ;
 ALTER TABLE match RENAME COLUMN fromneed TO fromatom ;
 ALTER TABLE match RENAME COLUMN toneed TO toatom ;
 ALTER TABLE facet RENAME COLUMN needuri TO atomuri ;
 ALTER TABLE facet RENAME COLUMN faceturi TO socketuri ;
 ALTER TABLE facet RENAME COLUMN defaultfacet TO defaultsocket ;
 ALTER TABLE need_ownerapp RENAME COLUMN need_id TO atom_id ;
 ALTER TABLE wonuser_userneed RENAME COLUMN userneeds_id TO useratoms_id ;
 ALTER TABLE connection RENAME COLUMN needuri TO atomuri ;
 ALTER TABLE connection RENAME COLUMN remoteconnectionuri TO targetconnectionuri ;
 ALTER TABLE connection RENAME COLUMN remoteneeduri TO targetatomuri ;
 ALTER TABLE connection RENAME COLUMN parent_need_id TO parent_atom_id ;
 ALTER TABLE connection RENAME COLUMN event_container_id TO message_container_id ;
 ALTER TABLE connection RENAME COLUMN faceturi TO socketuri ;
 ALTER TABLE connection RENAME COLUMN remotefaceturi TO targetsocketuri ;
 ALTER TABLE connection_container RENAME COLUMN need_id TO atom_id ;
 ALTER TABLE event_container RENAME TO message_container ;
 ALTER TABLE need_rdf_datasets RENAME TO atom_rdf_datasets ;
 ALTER TABLE need RENAME TO atom ;
 ALTER TABLE facet RENAME TO socket ;
 ALTER TABLE need_ownerapp RENAME TO atom_ownerapp ;
 ALTER TABLE needdraft RENAME TO atomdraft ;
 ALTER TABLE userneed RENAME TO useratom ;
 ALTER TABLE wonuser_userneed RENAME TO wonuser_useratom ;
 ALTER INDEX event_container_pkey RENAME TO message_container_pkey ;
 ALTER INDEX idx_me_innermost_message_uri_receiver_need_uri RENAME TO idx_me_innermost_message_uri_recipient_atom_uri ;
 ALTER INDEX idx_need_unique_datasetholder_id RENAME TO idx_atom_unique_datasetholder_id ;
 ALTER INDEX idx_need_unique_event_container_id RENAME TO idx_atom_unique_message_container_id ;
 ALTER INDEX need_pkey RENAME TO atom_pkey ;
 ALTER INDEX idx_unique_facet RENAME TO idx_unique_socket ;
 ALTER INDEX facet_pkey RENAME TO socket_pkey ;
 ALTER INDEX idx_no_need_id RENAME TO idx_no_atom_id ;
 ALTER INDEX idx_no_unique_need_id_owner_application_id RENAME TO idx_no_unique_atom_id_owner_application_id ;
 ALTER INDEX needdraft_pkey RENAME TO atomdraft_pkey ;
 ALTER INDEX userneed_pkey RENAME TO useratom_pkey ;
 ALTER INDEX idx_connection_unique_event_container_id RENAME TO idx_connection_unique_message_container_id ;
 ALTER INDEX idx_connection_needuri_remoteneeduri RENAME TO idx_connection_atomuri_targetatomuri ;
