# The `Create` message of a need must not contain a reference
prefix msg: <http://purl.org/webofneeds/message#>
select ?msg where {
  ?msg msg:hasMessageType msg:CreateMessage;
	   msg:hasPreviousMessage ?msg.
}

