PREFIX won: <https://w3id.org/won/core#>
PREFIX s: <http://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT ?result ?score WHERE {
  BIND ((YEAR(?created) - 1970) * 315360000
       + MONTH(?created) * 26280000
       + DAY(?created) * 86400
       + HOURS(?created) * 3600
       + MINUTES(?created) * 60
       + SECONDS(?created)
        as ?score)
  ?result <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> won:Atom.
  ?result won:atomState  won:Active .
  ?result dct:created ?created.
}
