# Any message other than a `Create` message must contain at least one reference
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX msg: <https://w3id.org/won/message#>
PREFIX won: <https://w3id.org/won/core#>
SELECT * WHERE {
  ?msg msg:messageType ?msgType .
  FILTER NOT EXISTS {?msg msg:previousMessage ?msg2}
  FILTER (?msgType != msg:CreateMessage && ?msgType != msg:AtomCreatedNotificationMessage)
}
