# The `Create` message of an atom must not contain a reference
prefix msg: <https://w3id.org/won/message#>
select ?msg where {
  ?msg msg:messageType msg:CreateMessage;
	   msg:previousMessage ?msg.
}

