# There must be no directed circles in the graph
PREFIX msg: <https://w3id.org/won/message#>
SELECT ?msg WHERE {
  {
  	?msg msg:previousMessage ?msg .
  } UNION {
  	?msg msg:previousMessage ?msg2 .
  	?msg2 msg:previousMessage* ?msg
  }
}