# From any message, other than a `Create` message, there must be
# at least one path to the atom's `Create` message
PREFIX msg: <https://w3id.org/won/message#>
SELECT ?msg WHERE {
  ?msg msg:messageType ?msgType.
  FILTER NOT EXISTS {
    ?msg msg:previousMessage* ?createMsg.
    ?createMsg msg:messageType msg:CreateMessage.
  }
  FILTER (?msgType != msg:AtomCreatedNotificationMessage)
}
