# A Response must always reference the message that it is a response to.
PREFIX msg: <https://w3id.org/won/message#>
SELECT * WHERE {
  {
  	?resp a msg:FromSystem .
	?resp msg:isResponseTo ?msg .
  } UNION {
	?resp a msg:FromOwner .
	?resp msg:isResponseTo ?msg .
  } UNION {
	?resp a msg:FromExternal .
	?resp msg:isRemoteResponseTo ?msg .
  }
  {
  	?resp msg:messageType msg:SuccessResponse.
  } UNION {
    ?resp msg:messageType msg:FailureResponse.
  }
  FILTER NOT EXISTS {
  	?resp msg:previousMessage ?msg.
  }
}
