prefix s:     <http://schema.org/>

select ?lat ?lon

where {
	?main a s:TravelAction;
    	  s:fromLocation ?location.
  	?location a s:Place;
          s:geo ?geo.
  	?geo a s:GeoCoordinates;
          s:latitude ?lat;
          s:longitude ?lon.
}