prefix s:     <http://schema.org/>
prefix won:   <http://purl.org/webofneeds/model#>

Select ?lat ?lon

where {
	?main a s:Place;
          won:hasBoundingBox ?boundingBox .
    ?boundingBox won:hasNorthWestCorner ?geoCoordinates .
    ?geoCoordinates s:latitude ?lat;
                    s:longitude ?lon.
}