PREFIX con: <https://w3id.org/won/content#>
prefix s:     <http://schema.org/>
prefix won:   <https://w3id.org/won/core#>

Select ?lat ?lon

where {
	?main a s:Place;
          con:boundingBox ?boundingBox .
    ?boundingBox con:northWestCorner ?geoCoordinates .
    ?geoCoordinates s:latitude ?lat;
                    s:longitude ?lon.
}