prefix s:     <http://schema.org/>
prefix won:   <https://w3id.org/won/core#>

Select ?lat ?lon

where {
	?main a s:Place;
          won:boundingBox ?boundingBox .
    ?boundingBox won:southEastCorner ?geoCoordinates .
    ?geoCoordinates s:latitude ?lat;
                    s:longitude ?lon.
}