prefix s:     <http://schema.org/>

select ?lat ?lon ?name

where {
	?main a s:TravelAction;
    	  s:toLocation ?location.
  	?location a s:Place;
          s:geo ?geo;
          s:name ?name.
  	?geo a s:GeoCoordinates;
          s:latitude ?lat;
          s:longitude ?lon.
}