SELECT DISTINCT  *
WHERE
  { SELECT  ?result
    WHERE
      { ?result  a                     <http://purl.org/webofneeds/model#Need> ;
                 ?prop                 ?textSearchTarget
        FILTER contains(lcase(?textSearchTarget), "wtf")
        FILTER NOT EXISTS { ?result  <http://purl.org/webofneeds/model#hasFlag>  <http://purl.org/webofneeds/model#NoHintForCounterpart> }
      }
    OFFSET  0
    LIMIT   30
  }
