prefix dc:    <http://purl.org/dc/elements/1.1/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix conn:  <http://localhost:8080/won/resource/connection/>
prefix event: <http://localhost:8080/won/resource/event/>
prefix woncrypt: <https://w3id.org/won/core#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix local: <http://localhost:8080/won/resource/>
prefix won:   <https://w3id.org/won/core#>
prefix msg:   <https://w3id.org/won/message#>
prefix signature: <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#>
prefix ldp:   <http://www.w3.org/ns/ldp#>


# all 'fromSystem' envelopes should be signed by senderNode
#ASK
#{
  SELECT

    ?correctSysenvNum

    ?sysenvNum


    (if(?sysenvNum != ?correctSysenvNum, "FAIL", "OK") AS ?check)


  WHERE
  {


    # count fromSystem envelopes that have correct signers
    {SELECT
    (count(DISTINCT ?env) as ?correctSysenvNum)
    WHERE
    {
      GRAPH ?g1
      {
          ?event msg:senderNode    ?envsigner
      } .
      GRAPH ?g2
      {
          ?event a msg:FromSystem .
      } .
      GRAPH ?env
      {
          ?env a msg:EnvelopeGraph .
          ?env <http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf> ?event .
      } .
      GRAPH ?g3
      {
          ?envsig a signature:Signature .
          ?envsig msg:signedGraph ?env .
          ?envsig signature:hasVerificationCertificate ?envsigner .
      } .
    } ORDER BY ?event
    }

    # count all fromSystem envelopes
        {SELECT
        (count (DISTINCT ?g) AS ?sysenvNum)
        WHERE
        {
          GRAPH ?g
          {
              ?event a msg:FromSystem .
          } .
        }
        }

  }


#}