prefix dc:    <http://purl.org/dc/elements/1.1/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix conn:  <http://localhost:8080/won/resource/connection/>
prefix event: <http://localhost:8080/won/resource/event/>
prefix woncrypt: <https://w3id.org/won/core#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix local: <http://localhost:8080/won/resource/>
prefix won:   <https://w3id.org/won/core#>
prefix msg:   <https://w3id.org/won/message#>
prefix signature: <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#>
prefix ldp:   <http://www.w3.org/ns/ldp#>

# each signature graph should have required signature triples, including one link to envelope or content graph

  SELECT

    ?numSignatures
    ?numCorrectPropSignatures


    (if(?numCorrectPropSignatures != ?numSignatures, "FAIL", "OK") AS
    ?check)

  WHERE
  {


    # count number of signature graphs that have required properties
    { SELECT (count(distinct ?g) as ?numCorrectPropSignatures)
        WHERE
        {

          ?g rdf:type signature:Signature .
          ?g signature:signatureValue ?svalue .
          ?g signature:hasVerificationCertificate ?signer .
          ?g msg:signedGraph ?signed .
          ?g msg:publicKeyFingerprint ?fingerprint .
          ?g msg:hash ?hash
             }

     }


     # count number of signatures
    {  SELECT (count(?g) as ?numSignatures) WHERE
     {
		?g msg:signedGraph ?signed .
     }
    }




  }

