prefix dc:    <http://purl.org/dc/elements/1.1/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix conn:  <http://localhost:8080/won/resource/connection/>
prefix event: <http://localhost:8080/won/resource/event/>
prefix woncrypt: <https://w3id.org/won/core#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix local: <http://localhost:8080/won/resource/>
prefix won:   <https://w3id.org/won/core#>
prefix msg:   <https://w3id.org/won/message#>
prefix ldp:   <http://www.w3.org/ns/ldp#>
prefix rdfg:   <http://www.w3.org/2004/03/trix/rdfg-1/>

# any named graph in D should be either a signature graph or a signed graph.

#ASK
#{
  SELECT

	?numNeitherSignedNorSignature


    (if(?numNeitherSignedNorSignature = 0, "OK", "FAIL") AS ?check)

  WHERE
  {

   
    # count number of signature graphs that have corresponding signed graph
    { SELECT (count(distinct ?graphToCheck) as ?numNeitherSignedNorSignature)
        WHERE
        {
        	# select all graphs
        	{ SELECT ?graphToCheck 
        		WHERE 
	        	{
			    	GRAPH ?graphToCheck
		    		{
		        		?a ?b ?c
		        	} 
		    	}
        	}
        	# filter out those that are signed (either in a separate signature graph or in another graph)
	        FILTER NOT EXISTS 
	        {
	        	GRAPH ?any
	            {
	              ?g rdf:type msg::Signature .
	              ?g msg:signedGraph ?graphToCheck .
	            } .
			}
			# filter out hints (we allow for them not to be signed)
			FILTER NOT EXISTS 
	        {
	        	GRAPH ?graphToCheck
	            {
	        		?graphToCheck rdfg:subGraphOf ?event.
            		?event msg:messageType ?type.
            		filter (?type = msg:SocketHintMessage || ?type = msg:AtomHintMessage)
	            } .
			}
            
			# filter out those that are signature graphs
	        FILTER NOT EXISTS 
	        {
	        	GRAPH ?graphToCheck
	            {
	              ?graphToCheck rdf:type msg:Signature .
	              ?graphToCheck msg:signedGraph ?anotherGraph .
	            } .
			}
		}
     }




  }
#}