drop database won_node1;
drop database won_owner1;
drop database won_node2;
drop database won_owner2;
drop database won_node3;
drop database won_owner3;
drop database won_node4;
drop database won_owner4;
create database won_node1;
create database won_owner1;
create database won_node2;
create database won_owner2;
create database won_node3;
create database won_owner3;
create database won_node4;
create database won_owner4;
grant all privileges on database won_node1 to won;
grant all privileges on database won_owner1 to won;
grant all privileges on database won_node2 to won;
grant all privileges on database won_owner2 to won;
grant all privileges on database won_node3 to won;
grant all privileges on database won_owner3 to won;
grant all privileges on database won_node4 to won;
grant all privileges on database won_owner4 to won;